"""empty message

Revision ID: 06554e4facf2
Revises: 881d1ee0e95f
Create Date: 2022-05-01 20:50:10.175446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06554e4facf2'
down_revision = '881d1ee0e95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('similar_images', sa.Column('userId', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('similar_images', 'userId')
    # ### end Alembic commands ###
