"""empty message

Revision ID: 4390aef9a73d
Revises: 06554e4facf2
Create Date: 2022-05-07 10:50:58.321276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4390aef9a73d'
down_revision = '06554e4facf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('hash_chunk5', sa.String(length=20), nullable=False))
    op.add_column('photos', sa.Column('hash_chunk6', sa.String(length=20), nullable=False))
    op.add_column('photos', sa.Column('hash_chunk7', sa.String(length=20), nullable=False))
    op.add_column('photos', sa.Column('hash_chunk8', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'hash_chunk8')
    op.drop_column('photos', 'hash_chunk7')
    op.drop_column('photos', 'hash_chunk6')
    op.drop_column('photos', 'hash_chunk5')
    # ### end Alembic commands ###
