"""Initial migration.

Revision ID: 4b543e8b4030
Revises: 
Create Date: 2022-04-10 12:57:16.768146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b543e8b4030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('verified_email', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('given_name', sa.String(length=50), nullable=False),
    sa.Column('family_name', sa.String(length=50), nullable=False),
    sa.Column('picture', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('refresh_token', sa.String(length=200), nullable=False),
    sa.Column('token_uri', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=150), nullable=False),
    sa.Column('client_secret', sa.String(length=150), nullable=False),
    sa.Column('scopes', sa.String(length=150), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_oauth')
    # ### end Alembic commands ###
