"""empty message

Revision ID: 881d1ee0e95f
Revises: f3fc4ba34aed
Create Date: 2022-05-01 18:39:12.495770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881d1ee0e95f'
down_revision = 'f3fc4ba34aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('albumId', sa.String(length=50), nullable=False),
    sa.Column('baseUrl', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('hash_chunk1', sa.String(length=20), nullable=False),
    sa.Column('hash_chunk2', sa.String(length=20), nullable=False),
    sa.Column('hash_chunk3', sa.String(length=20), nullable=False),
    sa.Column('hash_chunk4', sa.String(length=20), nullable=False),
    sa.Column('have_found_similar_images', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
