"""empty message

Revision ID: b4b474b45a8c
Revises: 35c462169574
Create Date: 2022-04-14 14:32:30.217516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b474b45a8c'
down_revision = '35c462169574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_tracker',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('albumId', sa.String(length=50), nullable=False),
    sa.Column('similarImagesStatus', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_tracker')
    # ### end Alembic commands ###
