"""empty message

Revision ID: f3fc4ba34aed
Revises: b4b474b45a8c
Create Date: 2022-04-23 17:21:19.835066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fc4ba34aed'
down_revision = 'b4b474b45a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_images',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('imageId', sa.String(length=50), nullable=False),
    sa.Column('similarImageId', sa.String(length=50), nullable=False),
    sa.Column('similarityScore', sa.Float(precision=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_images')
    # ### end Alembic commands ###
